### ISSUE TITLE
Elevated and Bridge metro tracks don't have custom pillars

### ISSUE THREAD

**Issue by bloodypenguin** [bloodypenguin/Skylines-MetroOverhaulMod#9]
http://i.imgur.com/R7IuRgL.png

I would like elevated track pillars to look like this:
http://www.alexblock.net/blog/wp-content/uploads/2013/08/SBJ-1.jpg
And bridge track pillars to look like this:
http://www.fotolibra.com/gallery/188291/metro-bridge-byker-newcastle-upon-tyne-with-metro/
or like that:
https://commons.wikimedia.org/wiki/File:Metro_bridge_Kiev_2010_May.JPG

**Comment by andreharv** [comment]
Something must have not committed properly because I already have custom pillars.
http://community.simtropolis.com/forums/topic/70279-additional-public-transit/?do=findComment&comment=1635789.

I am going to change the way that they are implemented in the game.  Though I have heard that .crp files are a bit more efficient at packaging the content, I don't feel it is worth the headache of managing them.  They require to be moved to a different directory and renamed when deploying the mod and so it is impossible to test.  Also, I do not want to give the option to delete them from the asset manager and with imported .crp files I am not sure that that can be done so from now on, all pillars and accessories are getting baked into the mod.  I already did it with the custom pillars for the steel version and it seems to be working fine.

**Comment by nhatanh0475** [comment]
You want your brigde to look like that? I don't even have a pillar. When I build it, it fly with nothing to hold. Before playing, a not found pop up. It say: "Steel metro not found", "steel metro pillar not found" Even if it not pop up not found, I still didn't see any pillar below metro track (except for bride in the Fine road tool)

**Comment by Kilaparthi-Himanshu** [comment]
Did u get any solution for ur problem cause I am still facing the problem of floating tracks till now even after M.O.M v9.0

**Comment by CosignCosine** [comment]
Are you using the workshop version of MOM?

**Comment by Kilaparthi-Himanshu** [comment]
Nope

**Comment by Kilaparthi-Himanshu** [comment]
But I have all necessary assets activated

**Comment by ShonenAsh** [comment]
Basically the mod only works online [steam workshop]. I think the way the mod refers to the assets needs to be looked at because just having the assets in the Appdata folder doesn't work. With the 9.0 update, the number of popups for missing assets have reduced and MetroBridgePillar is the only one.
